insert into authors (id, name, photo, biography_short, biography_rest)
values (1, 'Drucie Goodbourn', 'card.jpg', 'Lorem ipsum Drucie Goodbourn dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (2, 'Marcia Aggiss', 'card.jpg', 'Lorem ipsum Marcia Aggiss dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (3, 'Giovanni Bigg', 'card.jpg', 'Lorem ipsum Giovanni Bigg dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (4, 'Duffie Eynon', 'card.jpg', 'Lorem ipsum Duffie Eynon dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (5, 'Anselma McKennan', 'card.jpg', 'Lorem ipsum Anselma McKennan dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (6, 'Gert Kira', 'card.jpg', 'Lorem ipsum Gert Kira dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (7, 'Clerc Djakovic', 'card.jpg', 'Lorem ipsum Clerc Djakovic dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (8, 'Stacee Elsy', 'card.jpg', 'Lorem ipsum Stacee Elsy dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (9, 'Dorotea Bonhill', 'card.jpg', 'Lorem ipsum Dorotea Bonhill dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (10, 'Minni Bunney', 'card.jpg', 'Lorem ipsum Minni Bunney dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (11, 'Berty Gandley', 'card.jpg', 'Lorem ipsum Berty Gandley dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (12, 'Raynard Tesdale', 'card.jpg', 'Lorem ipsum Raynard Tesdale dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (13, 'Joanna Hutfield', 'card.jpg', 'Lorem ipsum Joanna Hutfield dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (14, 'Dannie Glidder', 'card.jpg', 'Lorem ipsum Dannie Glidder dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (15, 'Timmie Adshede', 'card.jpg', 'Lorem ipsum Timmie Adshede dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (16, 'Fernando Neads', 'card.jpg', 'Lorem ipsum Fernando Neads dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (17, 'Teddy Guilliland', 'card.jpg', 'Lorem ipsum Teddy Guilliland dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (18, 'Paloma Grebert', 'card.jpg', 'Lorem ipsum Paloma Grebert dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (19, 'Kristos Usher', 'card.jpg', 'Lorem ipsum Kristos Usher dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (20, 'Darcey Rohmer', 'card.jpg', 'Lorem ipsum Darcey Rohmer dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (21, 'Cristie Isacsson', 'card.jpg', 'Lorem ipsum Cristie Isacsson dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (22, 'Lindsay Coutthart', 'card.jpg', 'Lorem ipsum Lindsay Coutthart dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (23, 'Helyn Schneidar', 'card.jpg', 'Lorem ipsum Helyn Schneidar dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (24, 'Bette-ann Askem', 'card.jpg', 'Lorem ipsum Bette-ann Askem dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
insert into authors (id, name, photo, biography_short, biography_rest)
values (25, 'Dom Robuchon', 'card.jpg', 'Lorem ipsum Dom Robuchon dolor sit amet, consectetur adipiscing elit.', 'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');

insert into books (author_id, title, priceOld, price) values (1, 'exploit real-time e-commerce', '$203.23', '$43.37');
insert into books (author_id, title, priceOld, price) values (2, 'utilize real-time interfaces', '$260.31', '$35.96');
insert into books (author_id, title, priceOld, price) values (3, 'extend strategic e-services', '$272.00', '$151.04');
insert into books (author_id, title, priceOld, price) values (4, 'iterate integrated solutions', '$271.58', '$141.40');
insert into books (author_id, title, priceOld, price) values (5, 'cultivate magnetic e-commerce', '$278.43', '$54.44');
insert into books (author_id, title, priceOld, price) values (6, 'architect vertical ROI', '$282.54', '$102.61');
insert into books (author_id, title, priceOld, price) values (7, 'disintermediate extensible architectures', '$295.38', '$181.27');
insert into books (author_id, title, priceOld, price) values (8, 'extend leading-edge methodologies', '$283.08', '$97.96');
insert into books (author_id, title, priceOld, price) values (9, 'integrate one-to-one systems', '$258.51', '$52.25');
insert into books (author_id, title, priceOld, price) values (10, 'revolutionize 24/7 infrastructures', '$260.79', '$33.69');
insert into books (author_id, title, priceOld, price) values (11, 'enhance innovative e-services', '$256.54', '$160.98');
insert into books (author_id, title, priceOld, price) values (12, 'maximize 24/365 e-tailers', '$262.07', '$34.06');
insert into books (author_id, title, priceOld, price) values (13, 'scale integrated architectures', '$257.66', '$32.97');
insert into books (author_id, title, priceOld, price) values (14, 'e-enable frictionless web services', '$288.19', '$90.52');
insert into books (author_id, title, priceOld, price) values (15, 'strategize B2B channels', '$232.27', '$44.83');
insert into books (author_id, title, priceOld, price) values (16, 'syndicate compelling deliverables', '$287.45', '$101.89');
insert into books (author_id, title, priceOld, price) values (17, 'utilize bleeding-edge users', '$281.37', '$146.21');
insert into books (author_id, title, priceOld, price) values (18, 'cultivate 24/365 networks', '$270.99', '$184.76');
insert into books (author_id, title, priceOld, price) values (19, 'embrace plug-and-play platforms', '$278.36', '$77.71');
insert into books (author_id, title, priceOld, price) values (20, 'target innovative paradigms', '$298.94', '$130.01');
insert into books (author_id, title, priceOld, price) values (21, 'generate open-source e-business', '$276.57', '$113.25');
insert into books (author_id, title, priceOld, price) values (22, 'implement user-centric e-markets', '$254.70', '$115.31');
insert into books (author_id, title, priceOld, price) values (23, 'utilize magnetic supply-chains', '$279.70', '$77.86');
insert into books (author_id, title, priceOld, price) values (24, 'e-enable dot-com supply-chains', '$297.83', '$110.15');
insert into books (author_id, title, priceOld, price) values (25, 'facilitate efficient eyeballs', '$232.30', '$131.48');
